[package]
name = "rax-ftp-server"
version = "0.1.0"
edition = "2024"

[dependencies]
env_logger = "0.11.8"
log = "0.4.27"
tokio = { version = "1.45.1", features = ["full"] }
config = "0.13"
serde = { version = "1.0", features = ["derive"] }
